language: ruby
rvm:
  - 2.4.1
cache: bundler
before_script:
  # Need to ensure development seed succeeds even though it's not an explicit
  # test. We immediately drop this DB when it succeeds to make way for our test
  # DB.
  - RAILS_ENV=development rake db:setup db:drop
  - RAILS_ENV=test rake db:create db:schema:load
